sonar.projectKey=hamza-unlu_isg-dokuman-yonetim-sistemi
sonar.organization=hamza-unlu

sonar.sources=controllers,middleware,routes,services,utils
sonar.tests=tests
sonar.exclusions=**/node_modules/**,**/coverage/**,**/public/**,**/views/**,**/uploads/**,**/mevzuat/**

# Coverage — sadece test yazılan dosyalar ölçülür
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/node_modules/**,**/tests/**,**/coverage/**,\
  seed.js,testScraper.js,app.js,server.js,\
  routes/**,services/**,utils/**
